package framework.Teleportation;

import lombok.Getter;

import static framework.Teleportation.Category.*;

public enum Location {
    CHICKENS("Chickens", Monsters),
    COWS("Cows", Monsters),
    MINOTAURS("Minotaurs", Monsters),
    ROCK("Rock Crabs", Monsters),
    SAND("Sand Crabs", Monsters),
    YAKS("Yaks", Monsters),
    EXPERIMENTS("Experiments", Monsters),
    DESERT("Desert Bandit Camp", Monsters),
    CAVE("Cave Horrors", Monsters),
    KALPHITES("Kalphites", Monsters),
    TUROTHS("Turoths", Monsters),
    DAGANNOTHS_WATERBIRTH("Dagannoths (Waterbirth)", Monsters),
    DAGANNOTHS_LIGHTHOUSE("Dagannoths (Lighthouse)", Monsters),
    DUST("Dust Devils", Monsters),
    ABERRANT("Aberrant Spectres", Monsters),
    HYDRAS("Hydras, Drakes, Wyrms", Monsters),
    KURASKS("Kurasks", Monsters),
    GARGOYLES("Gargoyles", Monsters),
    BLUE("Blue Dragons", Monsters),
    MUTATED("Mutated Bloodvelds", Monsters),
    ABYSSAL("Abyssal Demons", Monsters),
    CAVE_KRAKEN("Cave Kraken", Monsters),
    SKELETAL("Skeletal Wyverns", Monsters),
    LIZARDMAN_CAVERN("Lizardman Shamans (Cavern)", Monsters),
    LIZARDMAN_CANYON("Lizardman Shamans (Canyon)", Monsters),
    LIZARDMAN_TEMPLE("Lizardman Shamans (Temple)", Monsters),
    SMOKE("Smoke Devils", Monsters),
    DARK("Dark Beasts", Monsters),
    BLACK("Black Dragons", Monsters),
    IRON("Iron/Steel Dragons", Monsters),
    MITHRIL("Mithril Dragons", Monsters),
    BRUTAL("Brutal Black Dragons", Monsters),
    ADAMANT("Adamant & Rune Dragons", Monsters),

    ANCIENT("Ancient Cavern", Dungeons),
    ASGARNIAN("Asgarnian Ice Dungeon", Dungeons),
    APE("Ape Atoll", Dungeons),
    BARBARIAN("Barbarian Stronghold", Dungeons),
    BRIMHAVEN_DUNG("Brimhaven Dungeon", Dungeons),
    CATACOMBS("Catacombs of Kourend", Dungeons),
    CHASM("Chasm of Fire", Dungeons),
    CRABCLAW("Crabclaw Caves", Dungeons),
    EDGEVILLE_DUNG("Edgeville Dungeon", Dungeons),
    FORTHOS("Forthos Dungeon", Dungeons),
    GIANTS("Giants' Den", Dungeons),
    GODWARS("Godwars Dungeon", Dungeons),
    IORWERTH("Iorwerth Dungeon", Dungeons),
    ISLE("Isle of Souls Dungeon", Dungeons),
    JORMUNGAND("Jormungand's Prison", Dungeons),
    KALPHITE_CAVE("Kalphite Cave", Dungeons),
    KALPHITE_HIVE("Kalphite Hive", Dungeons),
    KARUULM("Karuulm Slayer Dungeon", Dungeons),
    KRAKEN("Kraken Cove", Dungeons),
    KRUK("Kruk's Dungeon", Dungeons),
    LIGHTHOUSE("Lighthouse", Dungeons),
    LITHKREN("Lithkren Vault", Dungeons),
    LUMBRIDGE_SWAMP_DUNG("Lumbridge Swamp Dungeon", Dungeons),
    MEIYERDITCH("Meiyerditch Laboratories", Dungeons),
    MOS("Mos Le'Harmless Dungeon", Dungeons),
    NIEVE("Nieve's Cave", Dungeons),
    OGRE("Ogre Enclave", Dungeons),
    RELLEKKA_DUNG("Rellekka Dungeon", Dungeons),
    SLAYER_TOWER("Slayer Tower", Dungeons),
    SMOKE_DUNG("Smoke Dungeon", Dungeons),
    STRONGHOLD("Stronghold of Security", Dungeons),
    TAVERLEY_DUNG("Taverley Dungeon", Dungeons),
    VARROCK_SEWERS("Varrock Sewers", Dungeons),
    WATERFALL("Waterfall Dungeon", Dungeons),
    YANILLE_DUNG("Yanille Dungeon", Dungeons),

    PRIFDDINAS_RABBIT("Prifddinas Rabbit", Bossing),
    OBOR("Obor", Bossing),
    BRYOPHYTA("Bryophyta", Bossing),
    JUDGE("Judge of Yama", Bossing),
    GIANT("Giant Mole", Bossing),
    XAMPHUR("Xamphur", Bossing),
    DEMONIC("Demonic Gorillas", Bossing),
    KING("King Black Dragon", Bossing),
    MUTANT("Mutant Tarn", Bossing),
    SARACHNIS("Sarachnis", Bossing),
    THERMONUCLEAR("Thermonuclear Smoke Devils", Bossing),
    DAGANNOTH("Dagannoth Kings", Bossing),
    MITHRIL_DRAGONS("Mithril Dragons", Bossing),
    CERBERUS("Cerberus", Bossing),
    SKOTIZO("Skotizo", Bossing),
    KALPHITE("Kalphite Queen", Bossing),
    ABYSSAL_SIRE("Abyssal Sire", Bossing),
    ADAMANT_AND_RUNE_DRAGONS("Adamant & Rune Dragons", Bossing),
    BARRELCHEST("Barrelchest", Bossing),
    VANSTROM("Vanstrom Klause", Bossing),
    ALCHEMICAL("Alchemical Hydra", Bossing),
    FRAGMENT("Fragment of Seren", Bossing),
    GOD("God Wars", Bossing),
    ZULRAH("Zulrah", Bossing),
    VORKATH("Vorkath", Bossing),
    CORPOREAL("Corporeal Beast", Bossing),
    NEX("Nex", Bossing),
    ZALCANO("Zalcano", Bossing),
    NIGHTMARE("Nightmare", Bossing),
    INFERNO("The Inferno", Bossing),
    RAIDS_ONE("Raids I: Chambers of Xeric", Bossing),
    RAIDS_TWO("Raids II: The Theatre of Blood", Bossing),

    AL("Al-Kharid", Cities),
    ARCEUUS("Arceuus", Cities),
    ARDOUGNE("Ardougne", Cities),
    BRIMHAVEN("Brimhaven", Cities),
    BURTHORPE("Burthorpe", Cities),
    CAMELOT("Camelot", Cities),
    CANIFIS("Canifis", Cities),
    CATHERBY("Catherby", Cities),
    DARKMEYER("Darkmeyer", Cities),
    DORGESH("Dorgesh-kaan", Cities),
    DRAYNOR("Draynor", Cities),
    DESERT_BANDIT_CAMP("Desert Bandit Camp", Cities),
    EDGEVILLE("Edgeville", Cities),
    FALADOR("Falador", Cities),
    FOSSIL("Fossil Island", Cities),
    HOSIDIUS("Hosidius", Cities),
    KARAMJA("Karamja", Cities),
    LAND("Land's End", Cities),
    LLETYA("Lletya", Cities),
    LOVAKENGJ("Lovakengj", Cities),
    LUMBRIDGE("Lumbridge", Cities),
    MISCELLANIA("Miscellania", Cities),
    MOUNT("Mount Karuulm", Cities),
    MOS_LEHARMLESS("Mos Le'Harmless", Cities),
    MYTHS("Myths' Guild Entrance", Cities),
    NARDAH("Nardah", Cities),
    NEITIZNOT("Neitiznot", Cities),
    PISCARILIUS("Piscarilius", Cities),
    PISCATORIS("Piscatoris", Cities),
    POLLNIVNEACH("Pollnivneach", Cities),
    PORT("Port Sarim", Cities),
    PRIFDDINAS("Prifddinas", Cities),
    RELLEKKA("Rellekka", Cities),
    RIMMINGTON("Rimmington", Cities),
    RUINS("Ruins of Unkah", Cities),
    SHAYZIEN("Shayzien", Cities),
    SHILO("Shilo Village", Cities),
    TAVERLEY("Taverley", Cities),
    TROLLHEIM("Trollheim", Cities),
    TYRAS("Tyras Camp", Cities),
    TZHAAR("Tzhaar City", Cities),
    VARROCK("Varrock", Cities),
    VER("Ver Sinhaza/Theatre of Blood", Cities),
    WEISS("Weiss", Cities),
    YANILLE("Yanille", Cities),
    ZUL("Zul-Andra", Cities),

    AGILITY_GNOME_COUSE("Agility: Gnome Course", Skilling),
    AGILITY_DRYNORE_ROODTOP("Agility: Draynor Rooftop", Skilling),
    AGILITY_ALKHARID_ROOFTOP("Agility: Al-Kharid Rooftop", Skilling),
    AGILITY_VARROCK_ROOFTOP("Agility: Varrock Rooftop", Skilling),
    AGILITY_BARB_OUTPOST("Agility: Barbarian Outpost", Skilling),
    AGILITY_CANIFIS_ROOFTOP("Agility: Canifis Rooftop", Skilling),
    AGILITY_SEERS_ROOFTOP("Agility: Seers Rooftop", Skilling),
    AGILITY_POLLNIVNEACH_ROOFTOP("Agility: Pollnivneach Rooftop", Skilling),
    AGILITY_PRIFDDINAS_COURSE("Agility: Prifddinas Agility Course", Skilling),
    AGILITY_RELLEKKA_ROOFTOP("Agility: Rellekka Rooftop", Skilling),
    AGILITY_ARDOUGNE_ROOFTOP("Agility: Ardougne Rooftop", Skilling),
    AGILITY_HOLLED_SEPULCHRE("Agility: Hallowed Sepulchre", Skilling),
    CRAFTING_GUILD("Crafting: Guild", Skilling),
    FARMING_GUILD("Farming: Guild", Skilling),
    FIREMAKING_WINTERTODT("Firemaking: Wintertodt", Skilling),
    FISHING_ANGLERFISH("Fishing: Anglerfish", Skilling),
    FISHING_CATHERBY("Fishing: Catherby", Skilling),
    FISHING_GUILD("Fishing: Guild", Skilling),
    FISHING_LAKE_MOLCH("Fishing: Lake Molch", Skilling),
    FISHING_OTTOS_GROTTO("Fishing: Otto's Grotto", Skilling),
    FISHING_TEMPOROSS("Fishing: Tempoross", Skilling),
    HUNTER_FELDIP_HILLS("Hunter: Feldip Hills", Skilling),
    HUNTER_HOUSE_ON_THE_HILL("Hunter: House on the Hill", Skilling),
    HUNTER_PURO_PURO("Hunter: Puro Puro", Skilling),
    MINING_AL_KHARID("Mining: Al-Kharid", Skilling),
    MINING_BRIMHAVEN_PENINSULA("Mining: Brimhaven Peninsula", Skilling),
    MINING_ESSENCE("Mining: Essence", Skilling),
    MINING_DAEYALT_ESSENCE("Mining: Daeyalt Essence", Skilling),
    MINING_GUILD("Mining: Guild", Skilling),
    MINING_QUARRY("Mining: Quarry", Skilling),
    MINING_MOTHERLODE_MINE("Mining: Motherlode Mine", Skilling),
    MINING_SALT_MINE("Mining: Salt Mine", Skilling),
    MINING_TRAHAERN_MINE("Mining: Trahaearn Mine", Skilling),
    MINING_VARROCK_MINE("Mining: Varrock Mine", Skilling),
    RUNECRAFTING_ABYSS("Runecrafting: Abyss", Skilling),
    RUNECRAFTING_DARK_ALTAR("Runecrafting: Dark Altar", Skilling),
    RUNECRAFTING_ASTRAL_ALTAR("Runecrafting: Astral Altar", Skilling),
    RUNECRAFTING_QUARANIA_ALTAR("Runecrafting: Ourania Altar", Skilling),
    SMITHING_VARROCK_ANVILS("Smithing: Varrock Anvils", Skilling),
    SMITHING_PORT_PHASMATYS_FURNACE("Smithing: Port Phasmatys Furnace", Skilling),
    SMITHING_BLAST_FURNACE("Smithing: Blast Furnace", Skilling),
    THIEVING_ROGUES_DEN("Thieving: Rogues' Den", Skilling),
    WOODCUTTING_GUILD("Woodcutting: Guild", Skilling),
    WOODCUTTING_SEERS_VILLAGE("Woodcutting: Seers Village", Skilling),
    AGILITY_WILDERNESS_AGILITY_COURSE("Wilderness: Agility Course", Skilling),

    BARROWS("Barrows", Minigames),
    BLAST_FURNACE("Blast Furnace", Minigames),
    CASTLE_WARS("Castle Wars", Minigames),
    CASTLE_WARS_OBSERVATORY("Castle Wars: Observatory", Minigames),
    DUEL_ARENA("Duel Arena", Minigames),
    FIGHT_CAVES("Fight Caves", Minigames),
    GAMBLING("Gambling", Minigames),
    GAUNTLET("Gauntlet", Minigames),
    HALLOWED_SEPULCHRE("Hallowed Sepulchre", Minigames),
    LAST_MAN_STANDING("Last Man Standing", Minigames),
    MOTHERLODE_MINE("Motherlode Mine", Minigames),
    PARTY_ROOM("Party Room", Minigames),
    PEST_CONTROL("Pest Control", Minigames),
    PURO_PURO("Puro Puro", Minigames),
    PYRAMID_PLUNDER("Pyramid Plunder", Minigames),
    SOUL_WARS("Soul Wars", Minigames),
    TEARS_OF_GUTHIX("Tears of Guthix", Minigames),
    TEMPOROSS("Tempoross", Minigames),
    TOURNAMENT("Tournament", Minigames),
    WARRIOR_GUILD("Warrior's Guild", Minigames),
    WINTERTODT("Wintertodt", Minigames);

    @Getter
    private final String name;
    @Getter
    private final Category category;

    private Location(String name, Category category)
    {
        this.name = name;
        this.category = category;
    }
}